version: '3.6'

volumes:
  grafana-storage:

services:
  db:
    image: mysql:8-debian
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'api'
      MYSQL_USER: 'api'
      MYSQL_PASSWORD: 'api'

  prometheus:
    image: bitnami/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 4000:3000
    volumes:
      - grafana-storage:/var/lib/grafana

    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
      GF_SECURITY_ADMIN_PASSWORD: "admin"

  api:
    build: .
    ports:
      - 3000:3000
    environment:
      - JAMIE_API_DATABASE_HOST=db
      - JAMIE_API_DATABASE_PORT=3306
      - JAMIE_API_DATABASE_NAME=api
      - JAMIE_API_DATABASE_USER=api
      - JAMIE_API_DATABASE_PASSWORD=api
  

