global:
  scrape_interval: 15s
  evaluation_interval: 15s


# rules_file:
#   - "golden_signals.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jamie_api'
    static_configs:
      - targets: ['api:3000']

    # relabel_configs:
    #   - source_labels: [__name__]
    #     regex: '^(http_request_duration_seconds|http_request_size_bytes|http_response_size_bytes|error_total|saturation_total)$'
    #     action: keep
    #   - source_labels: [__name__]
    #     regex: '^(http_request_duration_seconds)$'
    #     target_label: 'request_duration'
    #     replacement: '$1'
    #   - source_labels: [__name__]
    #     regex: '^(http_request_size_bytes)$'
    #     target_label: 'request_size'
    #     replacement: '$1'
    #   - source_labels: [__name__]
    #     regex: '^(http_response_size_bytes)$'
    #     target_label: 'response_size'
    #     replacement: '$1'
    #   - source_labels: [__name__]
    #     regex: '^(error_total)$'
    #     target_label: 'errors'
    #     replacement: '$1'
    #   - source_labels: [__name__]
    #     regex: '^(saturation_total)$'
    #     target_label: 'saturation'
    #     replacement: '$1'