global:
  scrape_interval: 10s 

scrape_configs:
  - job_name: "prometheus_master"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "jamie_api"
    static_configs:
      - targets: [localhost:3000]
